DROP TABLE IF EXISTS frog;
DROP TABLE IF EXISTS candy;
DROP TABLE IF EXISTS mexicanfood;
DROP TABLE IF EXISTS videogames;
DROP TABLE IF EXISTS bots;

CREATE TABLE frog (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
frog TEXT NOT NULL,
cuteness TEXT
);

CREATE TABLE candy (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
candy TEXT NOT NULL,
sweet TEXT,
sour TEXT
);

CREATE TABLE mexicanfood (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
food TEXT NOT NULL,
spicy TEXT,
burrito TEXT,
taco TEXT
);


CREATE TABLE bots (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name TEXT NOT NULL,
sign TEXT,
sweet TEXT,
sassy TEXT
);


CREATE TABLE videogames (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name TEXT NOT NULL,
type TEXT,
difficulty TEXT,
recommend TEXT
);
